### ISSUE TITLE
How 1x1 Convs are equivalent to Fully Connected

### ISSUE THREAD

**Issue by filipetrocadoferreira** [VisualComputingInstitute/towards-reid-tracking#1]
My main doubt is how final 1x1 convs and the flatten fully connected original layers are related. You simply share the same weights? What is the output in both cases?

btw, Great Paper! Hope to see finally end-2-end deep tracking!

**Comment by lucasb-eyer** [comment]
Hi, sorry for the very late reply! :smile: I wasn't watching the repo for some reason!

Yes, one can exactly transform the fully-connected operation into a 1x1 conv, they are mathematically exactly the same. Simple reshaping of weights will do. Let's say you have an output of shape 3x3x128, flatten it to 1152, and then put a 1152->512 FC after it, and then a 512->128 FC after that. You can do the exact same by putting a 3x3x128->512 conv (no padding) and then a 1x1x512->128 conv (no padding). If you draw/write on a paper what these do, you'll see they are exactly the same.

Also, I'm writing up now, so unfortunately I won't be finishing this line of work, but I'm hopeful as it seems some people from the next generation want to pick it up :smile:

Closing this issue, but feel free to ask more.
